@startuml

left to right direction
rectangle {
    (Mostrar menú) as MM
    (Pedir comida) as PC
}

:Cliente: as Cl
:Restaurante: as Re
(Entregar comida) as EC

Cl -- MM
Cl -- PC
Re -- MM
Re -down- EC

@enduml
